import { Metadata } from 'next';
import Link from 'next/link';



import { 
  ArrowRight, Info, Database, User, CreditCard, Smartphone, 
  Activity, Eye, Share2, Link as LinkIcon, Clock, Globe, 
  Shield, Mail, Lock, Heart, AlertTriangle, Briefcase, FileText
} from 'lucide-react';

export const metadata: Metadata = { alternates: { canonical: '/privacy' },
  title: 'Privacy Policy | Vaitour',
  description: 'Detailed information regarding how Vaitour collects, uses, and protects your personal data.',
};

export default function PrivacyPolicyPage() {
  return (
    <div className="privacy-page-container" style={{ background: '#f8fafc', minHeight: '100vh', paddingBottom: '80px' }}>
      <style dangerouslySetInnerHTML={{ __html: `
        .privacy-hero-section { background: #0f172a; padding: 80px 24px; text-align: center; color: #fff; margin-bottom: 60px; }
        .privacy-hero-title { font-size: 3.5rem; font-weight: 900; margin-bottom: 20px; letter-spacing: -1px; color: #ffffff; }
        .privacy-hero-desc { font-size: 1.15rem; color: #cbd5e1; max-width: 750px; margin: 0 auto; line-height: 1.6; }
        
        .privacy-layout { max-width: 1200px; margin: 0 auto; padding: 0 24px; display: grid; grid-template-columns: minmax(280px, 1fr) 3fr; gap: 40px; align-items: start; }
        .privacy-sidebar { position: sticky; top: 100px; background: #fff; padding: 24px; border-radius: 12px; border: 1px solid #e2e8f0; max-height: calc(100vh - 120px); overflow-y: auto; }
        .privacy-main-content { background: #fff; padding: 40px; border-radius: 16px; border: 1px solid #e2e8f0; color: #334155; line-height: 1.8; }
        
        .contact-box { background: #f8fafc; padding: 24px; border-radius: 12px; border: 1px solid #e2e8f0; display: flex; align-items: center; justify-content: space-between; flex-wrap: wrap; gap: 16px; margin-top: 40px; }
        .contact-box-content { flex: 1 1 200px; }
        
        @media (max-width: 768px) {
          .privacy-hero-section { padding: 50px 16px; margin-bottom: 40px; }
          .privacy-hero-title { font-size: 2.2rem; }
          .privacy-hero-desc { font-size: 1rem; }
          
          .privacy-layout { grid-template-columns: 1fr; padding: 0 16px; gap: 24px; }
          .privacy-sidebar { position: static; max-height: none; margin-bottom: 0px; }
          .privacy-main-content { padding: 24px 16px; }
          .privacy-main-content h2 { align-items: flex-start !important; line-height: 1.4; }
          .privacy-main-content h2 svg { flex-shrink: 0; margin-top: 4px; }
          
          .contact-box { flex-direction: column; text-align: center; }
          .contact-box a { width: 100%; justify-content: center; }
        }
      `}} />
      {/* HERO SECTION */}
      <div className="privacy-hero-section">
        <h1 className="privacy-hero-title">Comprehensive Privacy Policy</h1>
        <p className="privacy-hero-desc">
          Your privacy is a fundamental human right. Review our comprehensive privacy guidelines to understand exactly how we collect, process, and fiercely protect your personal information within the Vaitour ecosystem.
        </p>
      </div>

      <div className="privacy-layout">
        
        {/* STICKY SIDEBAR (TABLE OF CONTENTS) */}
        <div className="privacy-sidebar">
          <h4 style={{ fontSize: '1rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', textTransform: 'uppercase', letterSpacing: '0.5px' }}>
            Privacy Details
          </h4>
          <ul style={{ listStyle: 'none', padding: 0, margin: 0, display: 'flex', flexDirection: 'column', gap: '12px' }}>
            <li><a href="#sec-1" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Data Collection Overview</a></li>
            <li><a href="#sec-2" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Personal Information</a></li>
            <li><a href="#sec-3" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Payment & Financial Data</a></li>
            <li><a href="#sec-4" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Device & Technical Data</a></li>
            <li><a href="#sec-5" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>How We Use Your Data</a></li>
            <li><a href="#sec-6" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Cookies & Tracking</a></li>
            <li><a href="#sec-7" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Data Sharing with Suppliers</a></li>
            <li><a href="#sec-8" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Third-Party Integrations</a></li>
            <li><a href="#sec-9" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Data Retention Limits</a></li>
            <li><a href="#sec-10" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Global Data Transfers</a></li>
            <li><a href="#sec-11" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Your Privacy Rights</a></li>
            <li><a href="#sec-12" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Opting Out of Marketing</a></li>
            <li><a href="#sec-13" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Security Measures</a></li>
            <li><a href="#sec-14" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Children's Privacy</a></li>
            <li><a href="#sec-15" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Data Breaches</a></li>
            <li><a href="#sec-16" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Dispute Resolution</a></li>
            <li><a href="#sec-17" style={{ color: '#475569', textDecoration: 'none', fontSize: '0.92rem', display: 'block' }}>Policy Updates</a></li>
          </ul>
        </div>

        {/* MAIN CONTENT AREA */}
        <div className="privacy-main-content card-panel">
          
          <div style={{ marginBottom: '32px', padding: '16px 20px', background: '#e0f2fe', borderRadius: '8px', borderLeft: '4px solid #0284c7', display: 'flex', gap: '12px', alignItems: 'flex-start' }}>
            <Info size={24} color="#0284c7" style={{ flexShrink: 0, marginTop: '2px' }} />
            <p style={{ margin: 0, color: '#0c4a6e', fontSize: '0.95rem' }}>
              <strong>Effective Date: August 2026.</strong> We strictly adhere to global privacy frameworks including GDPR (Europe) and CCPA (California). By using Vaitour, you consent to the comprehensive data practices, collection methodologies, and protective measures described deeply within this document.
            </p>
          </div>

          <section id="sec-1" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Database size={28} color="#0284c7" /> Data Collection Overview
            </h2>
            <p>At Vaitour, our approach to data collection is fundamentally rooted in the strict legal principle of "Data Minimization." This core philosophy dictates that data collection must be strictly tied to absolute operational necessity rather than speculative future use. We only collect the exact types of information required to facilitate your bookings, authenticate your digital identity across multiple devices, ensure your physical safety during active tours, and provide high-quality, uninterrupted customer support. We strongly and publicly oppose the pervasive industry practice of mass data harvesting. We never sell your personal profile, web browsing habits, or aggregated geographic data to external data brokers, advertising networks, or third-party marketing firms. Transparency is woven into the very fabric of our software engineering. You will always be explicitly notified when data is being collected through interactive, plain-English consent forms before any transmission occurs. Furthermore, our internal systems are regularly audited by independent privacy advocates to ensure our data collection mechanisms remain strictly aligned with our published policies, guaranteeing that your trust is never compromised.</p>
            <p style={{ marginTop: '16px' }}>To further cement this commitment, every single data point we request must undergo a rigorous internal "Data Protection Impact Assessment" (DPIA) conducted by our legal and engineering teams before it is ever coded into our application. This means that if an engineer wishes to add a new text field to a checkout form, they must formally prove that the data is indispensable for the completion of the tour or for your direct safety. If the data point is deemed merely "nice to have," the request is outright rejected by our compliance officers. We actively map the lifecycle of your dataâ€”from the millisecond it leaves your encrypted browser to the exact moment it is permanently purged from our cloud servers. We believe that digital autonomy is a modern human right, and our architecture reflects the belief that you should always remain the sole owner and master of your digital identity. We train every newly hired employee, from customer service agents to senior backend developers, in an intensive two-week privacy bootcamp that drills these principles into our corporate culture. We also mandate annual recertification on global privacy laws for all staff members. By establishing these hard, inflexible guardrails at the very foundation of our company, we ensure that your data is never treated as a monetizable commodity, but rather as a highly sensitive asset that has been temporarily entrusted to our care.</p>
          </section>

          <section id="sec-2" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <User size={28} color="#16a34a" /> Personal Information We Collect
            </h2>
            <p>When you register a new account, download our mobile application, or initiate a checkout process for a booking, you proactively provide us with basic personal details required to form a legally binding travel contract. We categorize this information into highly specific tiers to maintain granular access control. Core Identity Data includes your full legal name (exactly as it appears on your government-issued passport or national ID), your date of birth, and your primary spoken language. Contact Information encompasses your primary email address, an active mobile phone number capable of receiving SMS alerts, and your residential billing address. Specialized Booking Data is strictly situational; in highly specialized casesâ€”such as booking advanced scuba diving excursions, high-altitude mountaineering expeditions, or helicopter toursâ€”we may legally be required to collect physical metrics like exact weight for aircraft balance, height, and shoe size for specialized gear rental, alongside your emergency contact details. This information is legally mandatory to generate valid, binding booking tickets, ensure compliance with maritime and aviation safety laws, and populate accurate passenger manifests for our local suppliers.</p>
            <p style={{ marginTop: '16px' }}>It is critical to understand that not all of this data is collected simultaneously or generically across every interaction. We utilize a "Just-In-Time" (JIT) data collection methodology. For instance, we will never ask for your passport number or emergency contact when you are simply browsing a list of walking tours in Rome. Such sensitive fields will dynamically appear in your checkout flow only if you attempt to book a border-crossing excursion or a highly regulated adventure sport where local municipal laws legally demand that information. If you book a standard museum ticket, the system intentionally suppresses those data fields to maintain a minimalist footprint. Additionally, any uploaded documents, such as copies of a driver's license for an RV rental or a medical clearance certificate for skydiving, are automatically routed to a deeply encrypted, isolated storage vault. These documents are never reviewed by human eyes unless a supplier explicitly flags a legal requirement, and they are programmed to self-destruct from our servers exactly 48 hours after your tour safely concludes. We empower you to review exactly what personal data is currently attached to your profile via a centralized "Privacy Dashboard," allowing you to prune old phone numbers, outdated addresses, or historical travel companions with a single click, ensuring your live profile remains accurate, lean, and entirely under your direct control.</p>
          </section>

          <section id="sec-3" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <CreditCard size={28} color="#8b5cf6" /> Payment & Financial Data
            </h2>
            <p>Your financial security is our absolute highest priority. We explicitly do not process, transmit, or store your full 16-digit credit card numbers, CVV security codes, or bank account routing numbers on our internal databases under any circumstances. All financial transactions are processed instantly through highly secure, PCI-DSS Level 1 certified third-party payment gateways, including industry leaders such as Stripe, PayPal, Apple Pay, and Google Pay. When you enter your card details on our checkout page, they are immediately converted into a meaningless string of encrypted charactersâ€”known as Cryptographic Tokenizationâ€”by the payment processor before they even hit our servers. Vaitour only receives and stores this secure token. We strictly limit our retained identifiers to only the last four digits of your payment card, the card network (e.g., Visa, Mastercard), the expiration date, and the associated billing postal code. This specific, limited subset of data is solely utilized to verify legitimate refund requests, manage ongoing subscription billing, and execute automated anti-money laundering (AML) heuristics during the checkout flow to protect your identity from systemic theft.</p>
            <p style={{ marginTop: '16px' }}>The reliance on third-party tokenization means that even in the absolute worst-case scenario of a catastrophic breach of Vaitour's internal databases, the hackers would find absolutely zero actionable financial data. A cryptographic token is mathematically impossible to reverse-engineer into a usable credit card number outside of the specific payment processor's heavily fortified network. Furthermore, every single transaction routed through our platform undergoes an intense microsecond analysis by specialized artificial intelligence designed to detect fraudulent patterns. This AI analyzes hundreds of silent variablesâ€”such as the geographic distance between your IP address and the card's billing zip code, the velocity of recent purchases, and the historical reputation of the email address used. If a transaction is flagged with a high fraud probability score, it is automatically halted, and a manual secondary verification protocol is triggered to protect both the cardholder and our local suppliers from malicious chargebacks. We strictly adhere to the European Union's Revised Payment Services Directive (PSD2), meaning we fully support and mandate Strong Customer Authentication (SCA) workflows, such as 3D Secure, which require you to authorize high-value transactions via a biometric scan or a one-time password sent directly from your bank to your mobile device.</p>
          </section>

          <section id="sec-4" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Smartphone size={28} color="#dc2626" /> Device & Technical Data
            </h2>
            <p>To ensure our web application and mobile platforms function flawlessly across the globe, our servers automatically record specific technical metadata in the background the exact moment you access our domain. This dataset is absolutely critical for diagnosing complex software errors, optimizing server response times in remote regions, and ensuring frontend compatibility across thousands of different mobile device and browser combinations. The collected network identifiers include your anonymized IP address, which helps us automatically display the correct localized currency, calculate appropriate regional tax rates, and prevent unauthorized account access from unusual geographic locations. Hardware and software specs we record include your browser type and version engine, the core operating system architecture, the physical screen resolution and pixel density, and unique mobile device identifiers (such as the Apple IDFA or Android AdID, provided you have explicitly permitted this tracking in your device's native privacy settings). This technical data is heavily aggregated, immediately stripped of personally identifiable information (PII) upon ingestion, and purely used by our engineering and cybersecurity teams to detect software bugs, monitor server loads during peak holiday booking seasons, and proactively defend the platform against malicious Distributed Denial of Service (DDoS) attacks.</p>
            <p style={{ marginTop: '16px' }}>We treat this seemingly innocuous metadata with the exact same level of extreme security as we do your personal name or email address. We understand that in modern cybersecurity, metadata can be easily weaponized to build unauthorized shadow profiles of users through aggressive cross-site tracking. To combat this, we implement aggressive "IP Masking" protocols; the moment your IP address reaches our analytics servers, the last octet is permanently truncated (e.g., 192.168.1.xxx), rendering it mathematically impossible to trace the connection back to your specific household router or exact physical street address. Furthermore, the telemetry logs containing this hardware metadata are strictly configured with a highly aggressive Time-To-Live (TTL) expiration. This means that after a brief window of 14 daysâ€”which is precisely enough time for our engineering teams to analyze crash reports and push software patchesâ€”the raw technical logs are automatically purged from our servers entirely, leaving behind only broad, unidentifiable statistical dashboards. By enforcing these strict boundaries on technical data, we guarantee that your device fingerprint remains totally anonymous, completely un-targetable by advertising networks, and exclusively utilized to ensure your booking experience remains blazing fast, crash-free, and hyper-secure regardless of what device or network you are browsing from.</p>
          </section>

          <section id="sec-5" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Activity size={28} color="#d97706" /> How We Use Your Data
            </h2>
            <p>Your data is processed strictly and exclusively to deliver, improve, and secure the core operational features of the Vaitour experience. We firmly reject the industry norm of using customer data for invasive behavioral profiling or selling it to data brokers. Primarily, we use your information to successfully confirm your reservations, instantly generate your digital e-tickets, and dispatch critical, time-sensitive SMS or push notification updates regarding sudden tour delays, extreme localized weather warnings, or unexpected meeting point relocations. Furthermore, we actively utilize your data to facilitate secure, encrypted in-app communication channels between you and your local host, ensuring you can coordinate without ever exposing your real phone number. We also use your data to process your payments securely, issue lightning-fast automated refunds, and successfully mediate any complex financial or experiential disputes that may arise between you and a supplier after a trip concludes. Every single way we utilize your data is directly tied to honoring the legal contract of your travel booking and maximizing your physical safety while exploring foreign environments.</p>
            <p style={{ marginTop: '16px' }}>Secondarily, to dramatically enhance your personal user experience, we may carefully utilize highly anonymized behavioral data (such as the specific cities you frequently search for, the average price point you tend to book at, or the broad categories of tours you prefer, like "Culinary Tours" versus "Extreme Adventure Sports") to locally train our internal recommendation algorithms. This ensures that your personalized dashboard displays highly relevant, expertly curated travel experiences tailored specifically to your unique tastes. However, it is vital to note that this algorithmic profiling is done in a heavily siloed environment. The machine learning models operate entirely on generalized tokens and numerical vectors without ever exposing your actual name, email, or identity to the algorithm itself. If you prefer a completely chronological, unfiltered browsing experience, you have the absolute right to toggle off "Personalized Recommendations" deep within your privacy settings. Doing so will instantly instruct our servers to completely ignore your historical browsing behavior, defaulting your homepage back to a generic, globally popular feed of tours, ensuring you remain entirely in control of how your actions dictate your digital experience.</p>
          </section>

          <section id="sec-6" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Eye size={28} color="#06b6d4" /> Cookies & Tracking Tech
            </h2>
            <p>Like all modern digital platforms, Vaitour utilizes cookies, web beacons, embedded scripts, and local storage protocols to create a fast, seamless, and stateful browsing experience. We categorize these technologies into two distinct groups, ensuring you retain total, granular control over your digital footprint. Strictly Necessary (First-Party) Cookies are absolutely essential for the basic architecture of the website to function. They are heavily encrypted micro-files that keep your session securely logged in across multiple tabs, remember your preferred language and currency selections so you don't have to reset them on every page load, and maintain your shopping cart state as you navigate between different tour listings. Because these are critical to the mechanical operation of the site, they cannot be disabled without fundamentally breaking your ability to book a tour. Conversely, Analytics & Performance Cookies utilize strictly limited third-party technologies (such as Google Analytics 4, rigorously configured with mandatory IP anonymization enabled by default) to help us understand broad user navigation patterns, identify confusing UI bottlenecks, and measure exact page load speeds across different geographic regions.</p>
            <p style={{ marginTop: '16px' }}>We take a radical stance on tracking technology by absolutely refusing to deploy aggressive "Marketing" or "Cross-Site Tracking" cookies that follow you around the internet to serve you retargeted banner ads on other websites or social media feeds. You have the absolute, legally protected right to reject all non-essential cookies. Upon your very first visit to our domain, a highly visible, transparent cookie consent banner will appear, halting all non-essential scripts until you make a choice. This banner does not use deceptive "dark patterns" to trick you into accepting; the "Reject All" button is placed prominently alongside the "Accept" button. It allows you to granularly toggle exactly which specific trackers you permit based on your personal comfort level. These preferences are saved locally on your device and can be freely adjusted or completely revoked by navigating to the "Cookie Management" section in your account settings at any time, ensuring that your privacy boundaries are respected continuously, on every device, without degrading your core ability to safely browse and book travel experiences.</p>
          </section>

          <section id="sec-7" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Share2 size={28} color="#3b82f6" /> Data Sharing with Suppliers
            </h2>
            <p>Vaitour operates as a global technological marketplace, intricately connecting you with thousands of independent local operators, boutique hotels, and highly specialized experience providers. To successfully deliver a booked tour, expedition, or hotel stay, we are legally, operationally, and logically required to share a minimal, highly restricted subset of your data with the specific local supplier you have actively chosen to book with. This shared dataset is strictly and fiercely limited to your first and last name (to verify your identity upon arrival), your contact phone number (exclusively for emergency day-of-tour coordination, such as a local guide desperately trying to locate you at a crowded, chaotic meeting point), and any special physical requirements you explicitly noted during the checkout process (such as severe food allergies, stringent dietary restrictions, or the absolute need for wheelchair accessibility). We do not share your email address, your physical home address, or any of your payment details with these local suppliers, keeping a tight firewall between your sensitive identity and the third-party operator.</p>
            <p style={{ marginTop: '16px' }}>Suppliers on our platform are bound by extremely stringent, legally enforceable vendor contracts that govern exactly how they are permitted to handle this shared fragment of your data. They are strictly and unequivocally forbidden from selling this data to local marketing agencies, sharing it with their own third-party affiliated partners, or adding your phone number to their direct marketing SMS lists without obtaining your explicit, separate, and documented in-person consent. If a supplier is found to be abusing this dataâ€”for example, by messaging you promotions on WhatsApp weeks after your tour has concludedâ€”they are instantly subjected to severe financial penalties and permanent expulsion from the Vaitour marketplace. We provide suppliers with a specialized, deeply encrypted "Host Dashboard" where they view your details. Exactly 48 hours after your tour is marked as completed in our system, your personal phone number and full name are automatically redacted and permanently masked on their dashboard, ensuring that they cannot maintain a long-term shadow database of past guests, thereby securing your post-vacation privacy completely.</p>
          </section>

          <section id="sec-8" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <LinkIcon size={28} color="#14b8a6" /> Third-Party Integrations
            </h2>
            <p>To provide a frictionless, modern, and highly secure user experience, Vaitour strategically integrates with several external, highly vetted technology services and specialized API endpoints. If you choose the absolute convenience of creating an account or logging in using Single Sign-On (SSO) providers like Google, Apple, or Facebook, we will only request and collect the basic, minimum data permitted by those platforms (usually restricted entirely to your authenticated legal name, your verified email address, and a low-resolution profile picture). We categorically refuse to request sweeping permissions; we never gain access to your private passwords, your friends lists, your private social media posts, or your extended demographic data. By utilizing an SSO, you are simply using their highly secure cryptographic handshakes to verify your identity to us, vastly reducing the number of vulnerable passwords you need to manage across the internet.</p>
            <p style={{ marginTop: '16px' }}>Additionally, we integrate deeply with specialized enterprise fraud-detection services and elite cybersecurity vendors. These automated backend systems silently analyze your booking patterns, IP location discrepancies, hardware fingerprints, and behavioral metrics (such as the velocity of your typing or the speed at which you navigate the checkout form) in real-time. We want to be unequivocally clear: this intensive tracking is absolutely not for advertising, marketing, or behavioral profiling. It is a critical, mandatory security measure designed to instantly prevent stolen credit cards from being processed, to stop automated botnets from hoarding limited ticket inventory, and to protect both your stolen identity and our local suppliers from the devastating financial impact of sophisticated, coordinated fraudulent chargebacks. The data sent to these cybersecurity vendors is heavily encrypted, utilized strictly for a binary "Fraud/Not Fraud" determination, and is contractually forbidden from being retained, repurposed, or resold by the security vendor once the transaction analysis is complete.</p>
          </section>

          <section id="sec-9" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Clock size={28} color="#be123c" /> Data Retention Limits
            </h2>
            <p>We absolutely do not hoard your data indefinitely. The concept of forever-storage poses an unnecessary, reckless security risk and directly violates our core philosophy of data minimization. We actively retain your active personal information only for as long as your Vaitour account remains open, active, and in good standing. If you choose to formally delete your account via the privacy settings, your entire profile, associated reviews, and public-facing data are immediately and irreversibly removed from public view across the entire platform. Our system immediately severs the cryptographic links tying your identity to our active relational databases, rendering your account effectively invisible to all other users, hosts, and internal customer support agents within milliseconds of your confirmation.</p>
            <p style={{ marginTop: '16px' }}>However, upon complete account closure, we are legally and strictly mandated by overlapping global tax auditing frameworks, international accounting laws, and uncompromising anti-money laundering (AML) regulations to retain highly specific financial transaction records, finalized invoices, and historical booking receipts for a strict, non-negotiable statutory period of exactly 7 years. This retained financial data is immediately moved into a hyper-secure, deeply encrypted "Cold Storage" vault that is physically and digitally isolated from our main web servers, accessible only by a fraction of senior legal compliance officers under strict subpoena conditions. Once this mandatory 7-year statutory period successfully expires, an automated script awakens and your historical financial data is either permanently purged from our storage arrays using military-grade cryptographic deletion protocols (such as multipass secure erase algorithms), or heavily anonymizedâ€”stripped of all names, emails, and exact locationsâ€”so it can solely be used for broad, harmless statistical analysis (e.g., "Tour sales in Italy in 2026") without ever, under any mathematical circumstance, being linked back to your original identity.</p>
          </section>

          <section id="sec-10" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Globe size={28} color="#6366f1" /> Global Data Transfers
            </h2>
            <p>As a sprawling, highly interconnected international travel platform catering to a diverse global audience spanning hundreds of countries, your data must inevitably traverse international borders to function. It may be securely transferred to, routed through, and processed in centralized, highly secure enterprise data centers located outside of your immediate home country. Predominantly, Vaitour utilizes top-tier AWS (Amazon Web Services) and Google Cloud enterprise server clusters situated strategically within the United States, the United Kingdom, and the European Union to guarantee maximum geographic redundancy, lightning-fast load times, and 99.99% operational uptime. We recognize that national privacy laws and government surveillance statutes differ drastically by region, and the mere transfer of data across borders inherently creates complex legal and security vulnerabilities that must be rigorously managed.</p>
            <p style={{ marginTop: '16px' }}>To counter these vulnerabilities, we ensure that all cross-border data transfers are heavily protected by legally binding, internationally recognized frameworks. For our European users, we strictly implement Standard Contractual Clauses (SCCs) directly approved by the European Commission, and we fully adhere to the uncompromising principles of the EU-U.S. Data Privacy Framework. These dense legal mechanisms contractually and legally guarantee that your data receives an equivalent, unbreakable level of strict privacy protection, regardless of where the physical silicon servers processing it happen to reside. Furthermore, all data traveling between these intercontinental data centers is heavily encrypted in transit using advanced TLS 1.3 tunnels, meaning that even if the physical undersea fiber-optic cables were tapped by a malicious state actor, the intercepted data would remain an unreadable, mathematically unbreakable cipher. By layering these strict legal frameworks atop cutting-edge encryption technology, we ensure your fundamental privacy rights remain absolute, even as your data crosses the globe to finalize a booking.</p>
          </section>

          <section id="sec-11" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Shield size={28} color="#0ea5e9" /> Your Privacy Rights
            </h2>
            <p>Regardless of your geographic location, your citizenship, or the specific local laws of your home country, Vaitour extends the world's most stringent, aggressively pro-consumer privacy rightsâ€”primarily modeled directly after the European General Data Protection Regulation (GDPR) and the California Consumer Privacy Act (CCPA)â€”to all of our users globally. We firmly believe that privacy is a universal, non-negotiable human standard, not a regional privilege granted only to those in heavily regulated states. You possess powerful, legally actionable, and highly granular rights over every single byte of data you entrust to us. You have the absolute right to request a complete, structured, machine-readable digital copy of all information we hold about you (The Right to Data Portability), allowing you to audit exactly what we know, down to the timestamps of your logins.</p>
            <p style={{ marginTop: '16px' }}>Furthermore, you have the unalienable Right to Rectification, meaning you can demand the immediate, unquestioned correction of any historical inaccuracies in your profile, booking history, or billing records. You possess the Right to Restrict Processing, allowing you to temporarily freeze our ability to use your data if you are actively disputing its accuracy or legality. Most importantly, you hold the ultimate "Right to be Forgotten" (The Right to Erasure). By initiating a formal erasure request through your account settings or via our DPO, we are legally bound to completely delete your account, your profile, your saved preferences, and all non-financial historical data from our active servers within a strict 30-day legal window. We have engineered automated deletion pipelines that hunt down your data across all of our microservices, ensuring that when you ask to be forgotten, you are truly, comprehensively, and permanently erased from the Vaitour ecosystem.</p>
          </section>

          <section id="sec-12" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Mail size={28} color="#15803d" /> Opting Out of Marketing
            </h2>
            <p>You maintain total, unrestricted, and highly granular control over your personal inbox and all associated digital notification channels. We absolutely despise spam, and we operate on a strict "Opt-In" philosophy for all promotional materials. While we are legally and operationally required to send mandatory transactional communicationsâ€”such as booking confirmation tickets, sudden cancellation alerts, password reset links, or critical security notices regarding your accountâ€”marketing communications are entirely, 100% optional. We will never automatically subscribe you to a daily newsletter just because you booked a single walking tour, nor will we ever stealthily pass your email address to affiliated third-party travel blogs or airline partners without your explicit, separate consent.</p>
            <p style={{ marginTop: '16px' }}>You can opt out of all promotional newsletters, personalized destination recommendations, marketing SMS texts, and targeted in-app advertisements at any time, with zero friction and zero dark patterns. This can be instantly managed by clicking the highly visible, one-click "Unsubscribe" link located at the absolute bottom of any marketing email we send. Alternatively, you can dive into the comprehensive "Communication Preferences" dashboard deep within your account settings, where you can toggle specific types of messages on or off (e.g., keeping "Discount Codes" enabled, but turning off "Weekly Travel Inspiration"). We honor all unsubscribe requests instantaneously at the database level, with absolutely no frustrating 48-hour or 7-day waiting periods. Once you toggle a switch to off, our marketing servers will immediately, permanently cease sending you those specific communications.</p>
          </section>

          <section id="sec-13" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Lock size={28} color="#64748b" /> Security Measures
            </h2>
            <p>We deploy rigorous, uncompromising enterprise-grade security protocols designed to aggressively defend your data against unauthorized access, internal leaks, or sophisticated state-sponsored cyberattacks. Security at Vaitour is not an afterthought bolted on before launch; it is deeply architected into the very foundation of our infrastructure following the strict principles of "Zero Trust" architecture. All data transmitted between your personal deviceâ€”whether it's a smartphone on a public airport Wi-Fi or a secure home desktopâ€”and our cloud servers is fiercely end-to-end encrypted using the latest TLS 1.3 cryptographic protocols with Perfect Forward Secrecy (PFS). Furthermore, highly sensitive database fields (such as your hashed passwords, exact geolocation coordinates, and saved identity documents) are deeply encrypted at rest on our physical hard drives using military-grade AES-256 encryption algorithms, rendering stolen hard drives completely useless to thieves.</p>
            <p style={{ marginTop: '16px' }}>Internally, we operate under the principle of least privilege. Access to sensitive production user databases is strictly gated and entirely off-limits to 95% of our staff. For the elite engineering teams that do require access, they must navigate a gauntlet of security checks: requiring hardware-backed security keys (YubiKeys) for multi-factor authentication (MFA), strict Role-Based Access Control (RBAC), and access strictly funneled through a highly monitored Virtual Private Network (VPN) tunnel that logs every single keystroke and query executed. Furthermore, our entire global infrastructure undergoes routine, aggressive, and unannounced penetration testing (Red Teaming) and automated vulnerability scanning by independent, world-renowned third-party cybersecurity firms. These ethical hackers are paid specifically to try and break into our systems, allowing us to identify, isolate, and instantly patch zero-day exploits before they can ever be leveraged by malicious actors in the wild.</p>
          </section>

          <section id="sec-14" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Heart size={28} color="#4f46e5" /> Children's Privacy
            </h2>
            <p>The Vaitour platform, its expansive marketing campaigns, its user interface, and its complex booking engines are strictly designed for, and exclusively marketed to, adult travelers who are legally capable of forming binding financial contracts. We take the privacy and safety of minors with extreme, uncompromising seriousness. We do not knowingly collect, process, aggregate, or solicit any personal information whatsoever from children under the age of 16 (or the equivalent minimum age in your specific jurisdiction) without the explicit, highly verifiable, and documented consent of a parent or legal guardian. Our registration forms actively reject dates of birth that indicate the user is underage, and we utilize sophisticated behavioral heuristics to identify accounts that may have bypassed this check using falsified birth years.</p>
            <p style={{ marginTop: '16px' }}>If a parent, a legal guardian, a concerned educator, or our automated internal flagging system suspects that an underage child has successfully created an unauthorized account and provided us with their personal data, they are strongly encouraged to contact our specialized legal compliance team immediately through our priority channels. Upon swift verification of the claim, our protocol is absolute: we will immediately locate and permanently delete the associated data, instantly cancel and refund any pending bookings made by the minor, and permanently suspend the underage profile from ever accessing the platform again. These strict, unyielding measures ensure our total, unwavering compliance with the United States Children's Online Privacy Protection Act (COPPA), the strict age-gating requirements of the European GDPR, and similar global child protection statutes designed to keep minors safe from digital exploitation.</p>
          </section>

          <section id="sec-15" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <AlertTriangle size={28} color="#059669" /> Data Breaches & Notifications
            </h2>
            <p>While no digital system connected to the modern internet can ever be guaranteed to be 100% secure against highly sophisticated, rapidly evolving zero-day threats, Vaitour is heavily committed to a deeply ingrained corporate culture of radical transparency. We absolutely do not believe in hiding, downplaying, or obfuscating security incidents to protect our public relations image. In the highly unlikely and devastating event of a severe security breach that successfully bypasses our encryption and compromises your raw, unencrypted personal data, we have a meticulously drilled, military-style emergency incident response protocol already in place, ready to activate at a moment's notice.</p>
            <p style={{ marginTop: '16px' }}>We pledge a legally binding commitment to notify you directly via priority email, alongside all relevant global regulatory authorities (such as the EU Information Commissioner's Office and state-level Attorneys General), within a strict, maximum 72-hour window from the exact moment our security operations center confirms the breach. This official, public notification will not be hidden in legal jargon; it will include full, unfiltered, plain-English details of exactly what specific data fields were accessed, the vector of how the breach occurred, the potential identity theft risks to you as an individual, and the immediate, aggressive mitigation steps our engineering teams are actively taking to secure the perimeter. We will also provide you with immediate resources, such as complimentary credit monitoring services or direct lines to fraud prevention agencies, to ensure you are fully protected in the aftermath of the incident.</p>
          </section>

          <section id="sec-16" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <Briefcase size={28} color="#0284c7" /> Dispute Resolution
            </h2>
            <p>We take your privacy concerns, complaints, and formal data deletion requests with the absolute utmost seriousness, treating them with the same urgency as a critical financial dispute. If you ever believe that we have mishandled your data, ignored a valid GDPR deletion request, misinterpreted your consent preferences, or violated any specific clause laid out in this comprehensive policy, we ask that you contact our internal, independent Data Protection Officer (DPO) first. Our DPO operates autonomously from our marketing and engineering teams to ensure unbiased oversight. We pride ourselves on seeking rapid, highly amicable, and deeply responsive resolutions to all privacy concerns, aiming to solve the vast majority of issues within 48 hours without the exhausting need for legal escalation or arbitration.</p>
            <p style={{ marginTop: '16px' }}>However, we recognize that internal mediation is not always sufficient. If our internal review process leaves you dissatisfied, or if you believe we are fundamentally acting outside the bounds of the law, your rights remain fully protected and legally actionable. European users, for example, have the direct, unalienable right to completely bypass our internal teams and lodge a formal, legally binding complaint directly with their national Information Commissioner's Office (ICO) or their respective local, government-appointed data protection authority. These powerful regulatory bodies possess the absolute legal authority to aggressively audit our internal server logs, levy massive, crippling financial fines against our corporation, and legally force compliance on your behalf. We explicitly list this right here to remind you that you hold the ultimate power in this digital relationship, and we are held strictly accountable by the highest legal authorities in your jurisdiction.</p>
          </section>

          <section id="sec-17" style={{ marginBottom: '40px' }}>
            <h2 style={{ fontSize: '1.6rem', fontWeight: 800, color: '#0f172a', marginBottom: '16px', display: 'flex', alignItems: 'center', gap: '10px' }}>
              <FileText size={28} color="#d946ef" /> Policy Updates & Contact
            </h2>
            <p>As digital technology rapidly advances, as new and complex cyber threats continuously emerge from the shadows, and as global privacy laws aggressively evolve to protect consumers, so too will this Privacy Policy. It is a living, breathing document. Vaitour firmly reserves the unilateral right to carefully revise, expand, clarify, or update this document periodically to ensure continuous, airtight legal compliance across all international jurisdictions in which we operate. However, we make a solemn vow: we will never stealthily rewrite this policy to reduce your fundamental rights, expand our data harvesting capabilities, or sell your data without obtaining your explicit, opt-in consent for those specific new actions.</p>
            <p style={{ marginTop: '16px' }}>Whenever material changes are madeâ€”such as integrating a new category of third-party processor or altering our retention timelinesâ€”we will proactively notify all active users. This is not done via a silent website footer update, but rather via a direct, unavoidable email alert and a highly visible, blocking in-app notification that requires your acknowledgment before you can book your next tour. For any highly specific questions, formal data deletion requests, GDPR portability inquiries, or if you simply wish to speak with a human about how your data is routed, you can reach our dedicated legal team and Data Protection Officer directly via the contact options listed at the bottom of this page. Your continued use of the platform after these transparent updates signifies your ongoing, informed, and educated agreement to these constantly evolving, highly protective terms.</p>
          </section>

          <div className="contact-box">
            <div className="contact-box-content">
              <h4 style={{ margin: 0, fontSize: '1.1rem', color: '#0f172a', marginBottom: '4px' }}>Want to manage your data?</h4>
              <p style={{ margin: 0, fontSize: '0.95rem', color: '#64748b' }}>Contact our Data Protection Officer for data requests.</p>
            </div>
            <Link href="/contact" className="btn-primary" style={{ padding: '10px 24px', display: 'inline-flex', alignItems: 'center', gap: '8px' }}>
              <Mail size={18} />
              Contact Support
            </Link>
          </div>

        </div>
      </div>
    </div>
  );
}
